name: Sync default branch

on:
  push:
    branches: ["dev_*"]

permissions: {}

concurrency:
  group: sync-default-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    permissions: {}
    uses: workers-world/worker-actions/.github/workflows/worker-sync-default-dev-branch.yml@actions/v0.1.0
    secrets: inherit
    with:
      push_branch: ${{ github.ref_name }}
